/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Survey System API
 * API endpoints documentation for the Survey System, built by Daxho
 * OpenAPI spec version: 1.0.0
 */
export interface Error {
  type: string;
  status: number;
  title: string;
  detail: string;
  extensions?: unknown | null;
}

export interface SurveyStats {
  totalAnswers: number;
}

export interface User {
  id: string;
  email: string;
  /** @minLength 3 */
  username: string;
}

export interface UserSignup {
  email: string;
  /** @minLength 3 */
  username: string;
  /** @minLength 5 */
  password: string;
  /** @minLength 5 */
  passwordConfirm: string;
}

export interface UserLogin {
  email: string;
  /** @minLength 5 */
  password: string;
}

export type SurveyQuestionsItemType = typeof SurveyQuestionsItemType[keyof typeof SurveyQuestionsItemType];


export const SurveyQuestionsItemType = {
  SINGLE_SELECT: 'SINGLE_SELECT',
  MULTI_SELECT: 'MULTI_SELECT',
  TEXT_ANSWER: 'TEXT_ANSWER',
} as const;

export type SurveyQuestionsItemOptionsItem = {
  /** @minimum 1 */
  id: number;
  /** @minLength 1 */
  content: string;
};

export type SurveyQuestionsItem = {
  /** @minimum 1 */
  id: number;
  /** @minLength 5 */
  name: string;
  type: SurveyQuestionsItemType;
  /** @minItems 1 */
  options?: SurveyQuestionsItemOptionsItem[];
  isRequired: boolean;
};

export interface Survey {
  /** @minLength 1 */
  id: string;
  /** @minLength 5 */
  name: string;
  /** @minItems 1 */
  questions: SurveyQuestionsItem[];
  isActive: boolean;
  /** @nullable */
  deletedAt: string | null;
  createdAt: string;
  updatedAt: string;
  /** @minLength 1 */
  slug: string;
  /** @nullable */
  activatedAt: string | null;
}

export type CreateSurveyQuestionsItemType = typeof CreateSurveyQuestionsItemType[keyof typeof CreateSurveyQuestionsItemType];


export const CreateSurveyQuestionsItemType = {
  SINGLE_SELECT: 'SINGLE_SELECT',
  MULTI_SELECT: 'MULTI_SELECT',
  TEXT_ANSWER: 'TEXT_ANSWER',
} as const;

export type CreateSurveyQuestionsItemOptionsItem = {
  /** @minimum 1 */
  id: number;
  /** @minLength 1 */
  content: string;
};

export type CreateSurveyQuestionsItem = {
  /** @minimum 1 */
  id: number;
  /** @minLength 5 */
  name: string;
  type: CreateSurveyQuestionsItemType;
  /** @minItems 1 */
  options?: CreateSurveyQuestionsItemOptionsItem[];
  isRequired: boolean;
};

export interface CreateSurvey {
  /** @minLength 5 */
  name: string;
  /** @minItems 1 */
  questions: CreateSurveyQuestionsItem[];
}

export type UpdateSurvey = boolean;

export type RegisterUser200 = {
  data: User;
};

export type LoginUser200 = {
  data: User;
};

export type GetAllSurveysParams = {
search?: string;
page?: number;
limit?: number;
active?: boolean;
};

export type UpdateSurveyBySlugBodyQuestionsItemType = typeof UpdateSurveyBySlugBodyQuestionsItemType[keyof typeof UpdateSurveyBySlugBodyQuestionsItemType];


export const UpdateSurveyBySlugBodyQuestionsItemType = {
  SINGLE_SELECT: 'SINGLE_SELECT',
  MULTI_SELECT: 'MULTI_SELECT',
  TEXT_ANSWER: 'TEXT_ANSWER',
} as const;

export type UpdateSurveyBySlugBodyQuestionsItemOptionsItem = {
  /** @minimum 1 */
  id: number;
  /** @minLength 1 */
  content: string;
};

export type UpdateSurveyBySlugBodyQuestionsItem = {
  /** @minimum 1 */
  id: number;
  /** @minLength 5 */
  name: string;
  type: UpdateSurveyBySlugBodyQuestionsItemType;
  /** @minItems 1 */
  options?: UpdateSurveyBySlugBodyQuestionsItemOptionsItem[];
  isRequired: boolean;
};

export type UpdateSurveyBySlugBody = {
  /** @minLength 5 */
  name?: string;
  /** @minItems 1 */
  questions?: UpdateSurveyBySlugBodyQuestionsItem[];
  isActive?: UpdateSurvey;
};

export type CreateSurveyAnswerBodyResponsesItem = {
  id: number;
  content: string | number[];
};

export type CreateSurveyAnswerBody = {
  responses: CreateSurveyAnswerBodyResponsesItem[];
};

export type GetAllSurveyAnswers200Item = {
  id: string;
  responses?: unknown | null;
};

export type GetSurveyAnswerById200Data = {
  id: string;
  responses?: unknown | null;
};

export type GetSurveyAnswerById200 = {
  data: GetSurveyAnswerById200Data;
};

