/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Survey System API
 * API endpoints documentation for the Survey System, built by Daxho
 * OpenAPI spec version: 1.0.0
 */
export type ProblemErrorsItem = {
  field: string;
  message: string;
};

export interface Problem {
  type: string;
  status: number;
  title: string;
  detail: string;
  /** Only in 422 validation errors */
  errors?: ProblemErrorsItem[];
}

export type SurveyQuestionsItemType = typeof SurveyQuestionsItemType[keyof typeof SurveyQuestionsItemType];


export const SurveyQuestionsItemType = {
  SINGLE_SELECT: 'SINGLE_SELECT',
  MULTI_SELECT: 'MULTI_SELECT',
  TEXT_ANSWER: 'TEXT_ANSWER',
} as const;

export type SurveyQuestionsItemOptionsItem = {
  /** @minimum 1 */
  id: number;
  /** @minLength 1 */
  content: string;
};

export type SurveyQuestionsItem = {
  /** @minimum 1 */
  id: number;
  /** @minLength 5 */
  name: string;
  type: SurveyQuestionsItemType;
  /** @minItems 1 */
  options?: SurveyQuestionsItemOptionsItem[];
  isRequired: boolean;
};

export interface Survey {
  id: string;
  /** @minLength 5 */
  name: string;
  /** @minItems 1 */
  questions: SurveyQuestionsItem[];
  isActive: boolean;
  /** Set on first activation; name and questions become immutable */
  isLocked: boolean;
  /** @nullable */
  deletedAt: string | null;
  createdAt: string;
  /** @nullable */
  updatedAt: string | null;
  /** @minLength 1 */
  slug: string;
  /** @nullable */
  activatedAt: string | null;
}

export type OptionStatsOptionsItem = {
  optionContent: string;
  responseCount: number;
};

export interface OptionStats {
  questionId: number;
  questionName: string;
  options: OptionStatsOptionsItem[];
}

export interface SurveyStats {
  totalAnswers: number;
  completedAnswers: number;
  incompleteAnswers: number;
  questionCount: number;
  optionStats: OptionStats[];
}

export interface User {
  id: string;
  email: string;
  /** @minLength 3 */
  username: string;
}

export type UserAccount = User & ({
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
});

export interface UserLogin {
  email: string;
  /** @minLength 5 */
  password: string;
}

export type InvitationStatus = typeof InvitationStatus[keyof typeof InvitationStatus];


export const InvitationStatus = {
  pending: 'pending',
  accepted: 'accepted',
  revoked: 'revoked',
  expired: 'expired',
} as const;

/**
 * @nullable
 */
export type InvitationInvitedBy = {
  id: string;
  username: string;
} | null;

export interface Invitation {
  id: string;
  email: string;
  status: InvitationStatus;
  /** @nullable */
  invitedBy: InvitationInvitedBy;
  createdAt: string;
  expiresAt: string;
  /** @nullable */
  acceptedAt: string | null;
  /** @nullable */
  revokedAt: string | null;
}

export interface CreateInvitation {
  email: string;
}

export interface InvitationTokenInfo {
  email: string;
  expiresAt: string;
}

export interface AcceptInvitation {
  /**
     * @minLength 3
     * @maxLength 50
     */
  username: string;
  /** @minLength 5 */
  password: string;
  passwordConfirm: string;
}

export type CreateSurveyQuestionsItemType = typeof CreateSurveyQuestionsItemType[keyof typeof CreateSurveyQuestionsItemType];


export const CreateSurveyQuestionsItemType = {
  SINGLE_SELECT: 'SINGLE_SELECT',
  MULTI_SELECT: 'MULTI_SELECT',
  TEXT_ANSWER: 'TEXT_ANSWER',
} as const;

export type CreateSurveyQuestionsItemOptionsItem = {
  /** @minimum 1 */
  id: number;
  /** @minLength 1 */
  content: string;
};

export type CreateSurveyQuestionsItem = {
  /** @minimum 1 */
  id: number;
  /** @minLength 5 */
  name: string;
  type: CreateSurveyQuestionsItemType;
  /** @minItems 1 */
  options?: CreateSurveyQuestionsItemOptionsItem[];
  isRequired: boolean;
};

export interface CreateSurvey {
  /** @minLength 5 */
  name: string;
  /** @minItems 1 */
  questions: CreateSurveyQuestionsItem[];
}

export type AnswerResponsesItem = {
  id: number;
  content: string | number[];
};

export interface Answer {
  id: string;
  /** @nullable */
  surveyId: string | null;
  responses: AnswerResponsesItem[];
  originIp: string;
  createdAt: string;
  /** @nullable */
  deletedAt: string | null;
}

export type AnswerWithSurvey = Answer & ({
  /** @nullable */
  surveys: {
  name: string;
  questions: (unknown | null)[];
} | null;
});

export type LoginUser200 = {
  data: UserAccount;
};

export type GetCurrentUser200 = {
  data: User;
};

export type CreateInvitation201Data = {
  invitation: Invitation;
  token: string;
};

export type CreateInvitation201 = {
  data: CreateInvitation201Data;
};

export type GetAllInvitations200Meta = {
  results: number;
};

export type GetAllInvitations200 = {
  data: Invitation[];
  meta: GetAllInvitations200Meta;
};

export type GetInvitationByToken200 = {
  data: InvitationTokenInfo;
};

export type AcceptInvitation201 = {
  data: UserAccount;
};

export type GetAllSurveysParams = {
active?: GetAllSurveysActive;
search?: string;
/**
 * Creation day, DD/MM/YYYY
 */
date?: string;
/**
 * Positive integer
 */
page?: string;
/**
 * Positive integer
 */
limit?: string;
sort?: GetAllSurveysSort;
};

export type GetAllSurveysActive = typeof GetAllSurveysActive[keyof typeof GetAllSurveysActive];


export const GetAllSurveysActive = {
  true: 'true',
  false: 'false',
} as const;

export type GetAllSurveysSort = typeof GetAllSurveysSort[keyof typeof GetAllSurveysSort];


export const GetAllSurveysSort = {
  name: 'name',
  '-name': '-name',
  creation: 'creation',
  '-creation': '-creation',
} as const;

export type GetAllSurveys200Meta = {
  results: number;
  page: number;
  limit: number;
};

export type GetAllSurveys200 = {
  data: Survey[];
  meta: GetAllSurveys200Meta;
};

export type CreateSurvey201 = {
  data: Survey;
};

export type GetSurveyBySlug200 = {
  data: Survey;
};

export type UpdateSurveyBySlugBodyQuestionsItemType = typeof UpdateSurveyBySlugBodyQuestionsItemType[keyof typeof UpdateSurveyBySlugBodyQuestionsItemType];


export const UpdateSurveyBySlugBodyQuestionsItemType = {
  SINGLE_SELECT: 'SINGLE_SELECT',
  MULTI_SELECT: 'MULTI_SELECT',
  TEXT_ANSWER: 'TEXT_ANSWER',
} as const;

export type UpdateSurveyBySlugBodyQuestionsItemOptionsItem = {
  /** @minimum 1 */
  id: number;
  /** @minLength 1 */
  content: string;
};

export type UpdateSurveyBySlugBodyQuestionsItem = {
  /** @minimum 1 */
  id: number;
  /** @minLength 5 */
  name: string;
  type: UpdateSurveyBySlugBodyQuestionsItemType;
  /** @minItems 1 */
  options?: UpdateSurveyBySlugBodyQuestionsItemOptionsItem[];
  isRequired: boolean;
};

export type UpdateSurveyBySlugBody = {
  /** @minLength 5 */
  name?: string;
  /** @minItems 1 */
  questions?: UpdateSurveyBySlugBodyQuestionsItem[];
  isActive?: boolean;
};

export type UpdateSurveyBySlug200 = {
  data: Survey;
};

export type GetSurveyStatsBySlug200 = {
  data: SurveyStats;
};

export type CreateSurveyAnswerBodyResponsesItem = {
  id: number;
  content: string | number[];
};

export type CreateSurveyAnswerBody = {
  responses: CreateSurveyAnswerBodyResponsesItem[];
};

export type CreateSurveyAnswer201 = {
  data: Answer;
};

export type GetAllSurveyAnswers200Meta = {
  results: number;
};

export type GetAllSurveyAnswers200 = {
  data: Answer[];
  meta: GetAllSurveyAnswers200Meta;
};

export type GetSurveyAnswerById200 = {
  data: AnswerWithSurvey;
};

