/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Sondix API
 * API endpoints documentation for Sondix, built by Daxho
 * OpenAPI spec version: 1.0.0
 */
import {
  useQuery
} from '@tanstack/react-query';
import type {
  QueryFunction,
  QueryKey,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  GetSurveySummary200,
  Problem
} from '../sondixAPI.schemas';

import { customInstance } from '.././mutator/customInstance';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetSurveySummaryUrl = () => {




  return `/api/v1/stats/surveys`
}

/**
 * Counters over every non-deleted survey, ignoring the list filters (STAT-08).
 * @summary Count all and active surveys
 */
export const getSurveySummary = async ( options?: RequestInit): Promise<GetSurveySummary200> => {

  return customInstance<GetSurveySummary200>(getGetSurveySummaryUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSurveySummaryQueryKey = () => {
    return [
    `/api/v1/stats/surveys`
    ] as const;
    }


export const getGetSurveySummaryQueryOptions = <TData = Awaited<ReturnType<typeof getSurveySummary>>, TError = Problem>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSurveySummary>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSurveySummaryQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSurveySummary>>> = ({ signal }) => getSurveySummary({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSurveySummary>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSurveySummaryQueryResult = NonNullable<Awaited<ReturnType<typeof getSurveySummary>>>
export type GetSurveySummaryQueryError = Problem


/**
 * @summary Count all and active surveys
 */

export function useGetSurveySummary<TData = Awaited<ReturnType<typeof getSurveySummary>>, TError = Problem>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSurveySummary>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetSurveySummaryQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






