/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Survey System API
 * API endpoints documentation for the Survey System, built by Daxho
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateSurveyAnswerBody,
  Error,
  GetAllSurveyAnswers200Item,
  GetSurveyAnswerById200
} from '../surveySystemAPI.schemas';


type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;




export type createSurveyAnswerResponse200 = {
  data: void
  status: 200
}

export type createSurveyAnswerResponse400 = {
  data: Error
  status: 400
}

export type createSurveyAnswerResponse401 = {
  data: Error
  status: 401
}

export type createSurveyAnswerResponse404 = {
  data: Error
  status: 404
}

export type createSurveyAnswerResponse422 = {
  data: Error
  status: 422
}

export type createSurveyAnswerResponse500 = {
  data: Error
  status: 500
}

export type createSurveyAnswerResponseSuccess = (createSurveyAnswerResponse200) & {
  headers: Headers;
};
export type createSurveyAnswerResponseError = (createSurveyAnswerResponse400 | createSurveyAnswerResponse401 | createSurveyAnswerResponse404 | createSurveyAnswerResponse422 | createSurveyAnswerResponse500) & {
  headers: Headers;
};

export type createSurveyAnswerResponse = (createSurveyAnswerResponseSuccess | createSurveyAnswerResponseError)

export const getCreateSurveyAnswerUrl = (slug: string,) => {




  return `/api/v1/surveys/${slug}/answers`
}

/**
 * @summary Create an answer for a survey
 */
export const createSurveyAnswer = async (slug: string,
    createSurveyAnswerBody?: CreateSurveyAnswerBody, options?: RequestInit): Promise<createSurveyAnswerResponse> => {

  const res = await fetch(getCreateSurveyAnswerUrl(slug),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createSurveyAnswerBody)
  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: createSurveyAnswerResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as createSurveyAnswerResponse
}




export const getCreateSurveyAnswerMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSurveyAnswer>>, TError,{slug: string;data?: CreateSurveyAnswerBody}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof createSurveyAnswer>>, TError,{slug: string;data?: CreateSurveyAnswerBody}, TContext> => {

const mutationKey = ['createSurveyAnswer'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSurveyAnswer>>, {slug: string;data?: CreateSurveyAnswerBody}> = (props) => {
          const {slug,data} = props ?? {};

          return  createSurveyAnswer(slug,data,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateSurveyAnswerMutationResult = NonNullable<Awaited<ReturnType<typeof createSurveyAnswer>>>
    export type CreateSurveyAnswerMutationBody = CreateSurveyAnswerBody | undefined
    export type CreateSurveyAnswerMutationError = Error

    /**
 * @summary Create an answer for a survey
 */
export const useCreateSurveyAnswer = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSurveyAnswer>>, TError,{slug: string;data?: CreateSurveyAnswerBody}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createSurveyAnswer>>,
        TError,
        {slug: string;data?: CreateSurveyAnswerBody},
        TContext
      > => {
      return useMutation(getCreateSurveyAnswerMutationOptions(options));
    }
    export type getAllSurveyAnswersResponse200 = {
  data: GetAllSurveyAnswers200Item[]
  status: 200
}

export type getAllSurveyAnswersResponse400 = {
  data: Error
  status: 400
}

export type getAllSurveyAnswersResponse401 = {
  data: Error
  status: 401
}

export type getAllSurveyAnswersResponse404 = {
  data: Error
  status: 404
}

export type getAllSurveyAnswersResponse422 = {
  data: Error
  status: 422
}

export type getAllSurveyAnswersResponse500 = {
  data: Error
  status: 500
}

export type getAllSurveyAnswersResponseSuccess = (getAllSurveyAnswersResponse200) & {
  headers: Headers;
};
export type getAllSurveyAnswersResponseError = (getAllSurveyAnswersResponse400 | getAllSurveyAnswersResponse401 | getAllSurveyAnswersResponse404 | getAllSurveyAnswersResponse422 | getAllSurveyAnswersResponse500) & {
  headers: Headers;
};

export type getAllSurveyAnswersResponse = (getAllSurveyAnswersResponseSuccess | getAllSurveyAnswersResponseError)

export const getGetAllSurveyAnswersUrl = (slug: string,) => {




  return `/api/v1/surveys/${slug}/answers`
}

/**
 * @summary Get all answers for a survey
 */
export const getAllSurveyAnswers = async (slug: string, options?: RequestInit): Promise<getAllSurveyAnswersResponse> => {

  const res = await fetch(getGetAllSurveyAnswersUrl(slug),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getAllSurveyAnswersResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getAllSurveyAnswersResponse
}





export const getGetAllSurveyAnswersQueryKey = (slug: string,) => {
    return [
    `/api/v1/surveys/${slug}/answers`
    ] as const;
    }


export const getGetAllSurveyAnswersQueryOptions = <TData = Awaited<ReturnType<typeof getAllSurveyAnswers>>, TError = Error>(slug: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllSurveyAnswers>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllSurveyAnswersQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllSurveyAnswers>>> = ({ signal }) => getAllSurveyAnswers(slug, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllSurveyAnswers>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllSurveyAnswersQueryResult = NonNullable<Awaited<ReturnType<typeof getAllSurveyAnswers>>>
export type GetAllSurveyAnswersQueryError = Error


/**
 * @summary Get all answers for a survey
 */

export function useGetAllSurveyAnswers<TData = Awaited<ReturnType<typeof getAllSurveyAnswers>>, TError = Error>(
 slug: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllSurveyAnswers>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAllSurveyAnswersQueryOptions(slug,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type getSurveyAnswerByIdResponse200 = {
  data: GetSurveyAnswerById200
  status: 200
}

export type getSurveyAnswerByIdResponse400 = {
  data: Error
  status: 400
}

export type getSurveyAnswerByIdResponse401 = {
  data: Error
  status: 401
}

export type getSurveyAnswerByIdResponse404 = {
  data: Error
  status: 404
}

export type getSurveyAnswerByIdResponse422 = {
  data: Error
  status: 422
}

export type getSurveyAnswerByIdResponse500 = {
  data: Error
  status: 500
}

export type getSurveyAnswerByIdResponseSuccess = (getSurveyAnswerByIdResponse200) & {
  headers: Headers;
};
export type getSurveyAnswerByIdResponseError = (getSurveyAnswerByIdResponse400 | getSurveyAnswerByIdResponse401 | getSurveyAnswerByIdResponse404 | getSurveyAnswerByIdResponse422 | getSurveyAnswerByIdResponse500) & {
  headers: Headers;
};

export type getSurveyAnswerByIdResponse = (getSurveyAnswerByIdResponseSuccess | getSurveyAnswerByIdResponseError)

export const getGetSurveyAnswerByIdUrl = (slug: string,
    id: string,) => {




  return `/api/v1/surveys/${slug}/answers/${id}`
}

/**
 * @summary Get answer by ID
 */
export const getSurveyAnswerById = async (slug: string,
    id: string, options?: RequestInit): Promise<getSurveyAnswerByIdResponse> => {

  const res = await fetch(getGetSurveyAnswerByIdUrl(slug,id),
  {
    ...options,
    method: 'GET'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: getSurveyAnswerByIdResponse['data'] = body ? JSON.parse(body) : {}
  return { data, status: res.status, headers: res.headers } as getSurveyAnswerByIdResponse
}





export const getGetSurveyAnswerByIdQueryKey = (slug: string,
    id: string,) => {
    return [
    `/api/v1/surveys/${slug}/answers/${id}`
    ] as const;
    }


export const getGetSurveyAnswerByIdQueryOptions = <TData = Awaited<ReturnType<typeof getSurveyAnswerById>>, TError = Error>(slug: string,
    id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSurveyAnswerById>>, TError, TData>, fetch?: RequestInit}
) => {

const {query: queryOptions, fetch: fetchOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSurveyAnswerByIdQueryKey(slug,id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSurveyAnswerById>>> = ({ signal }) => getSurveyAnswerById(slug,id, { signal, ...fetchOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined && id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSurveyAnswerById>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSurveyAnswerByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getSurveyAnswerById>>>
export type GetSurveyAnswerByIdQueryError = Error


/**
 * @summary Get answer by ID
 */

export function useGetSurveyAnswerById<TData = Awaited<ReturnType<typeof getSurveyAnswerById>>, TError = Error>(
 slug: string,
    id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSurveyAnswerById>>, TError, TData>, fetch?: RequestInit}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetSurveyAnswerByIdQueryOptions(slug,id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type deleteSurveyAnswerByIdResponse204 = {
  data: void
  status: 204
}

export type deleteSurveyAnswerByIdResponse400 = {
  data: Error
  status: 400
}

export type deleteSurveyAnswerByIdResponse401 = {
  data: Error
  status: 401
}

export type deleteSurveyAnswerByIdResponse404 = {
  data: Error
  status: 404
}

export type deleteSurveyAnswerByIdResponse422 = {
  data: Error
  status: 422
}

export type deleteSurveyAnswerByIdResponse500 = {
  data: Error
  status: 500
}

export type deleteSurveyAnswerByIdResponseSuccess = (deleteSurveyAnswerByIdResponse204) & {
  headers: Headers;
};
export type deleteSurveyAnswerByIdResponseError = (deleteSurveyAnswerByIdResponse400 | deleteSurveyAnswerByIdResponse401 | deleteSurveyAnswerByIdResponse404 | deleteSurveyAnswerByIdResponse422 | deleteSurveyAnswerByIdResponse500) & {
  headers: Headers;
};

export type deleteSurveyAnswerByIdResponse = (deleteSurveyAnswerByIdResponseSuccess | deleteSurveyAnswerByIdResponseError)

export const getDeleteSurveyAnswerByIdUrl = (slug: string,
    id: string,) => {




  return `/api/v1/surveys/${slug}/answers/${id}`
}

/**
 * @summary Delete answer by ID
 */
export const deleteSurveyAnswerById = async (slug: string,
    id: string, options?: RequestInit): Promise<deleteSurveyAnswerByIdResponse> => {

  const res = await fetch(getDeleteSurveyAnswerByIdUrl(slug,id),
  {
    ...options,
    method: 'DELETE'


  }
)


  const body = [204, 205, 304].includes(res.status) ? null : await res.text();

  const data: deleteSurveyAnswerByIdResponse['data'] = body ? JSON.parse(body) : undefined
  return { data, status: res.status, headers: res.headers } as deleteSurveyAnswerByIdResponse
}




export const getDeleteSurveyAnswerByIdMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSurveyAnswerById>>, TError,{slug: string;id: string}, TContext>, fetch?: RequestInit}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSurveyAnswerById>>, TError,{slug: string;id: string}, TContext> => {

const mutationKey = ['deleteSurveyAnswerById'];
const {mutation: mutationOptions, fetch: fetchOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, fetch: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSurveyAnswerById>>, {slug: string;id: string}> = (props) => {
          const {slug,id} = props ?? {};

          return  deleteSurveyAnswerById(slug,id,fetchOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteSurveyAnswerByIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSurveyAnswerById>>>

    export type DeleteSurveyAnswerByIdMutationError = Error

    /**
 * @summary Delete answer by ID
 */
export const useDeleteSurveyAnswerById = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSurveyAnswerById>>, TError,{slug: string;id: string}, TContext>, fetch?: RequestInit}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteSurveyAnswerById>>,
        TError,
        {slug: string;id: string},
        TContext
      > => {
      return useMutation(getDeleteSurveyAnswerByIdMutationOptions(options));
    }
