/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Survey System API
 * API endpoints documentation for the Survey System, built by Daxho
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateSurveyAnswer201,
  CreateSurveyAnswerBody,
  GetAllSurveyAnswers200,
  GetSurveyAnswerById200,
  Problem
} from '../surveySystemAPI.schemas';

import { customInstance } from '.././mutator/customInstance';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getCreateSurveyAnswerUrl = (slug: string,) => {




  return `/api/v1/surveys/${slug}/answers`
}

/**
 * Public. One answer per IP and survey; inactive surveys return 404.
 * @summary Submit an answer to a survey
 */
export const createSurveyAnswer = async (slug: string,
    createSurveyAnswerBody?: CreateSurveyAnswerBody, options?: RequestInit): Promise<CreateSurveyAnswer201> => {

  return customInstance<CreateSurveyAnswer201>(getCreateSurveyAnswerUrl(slug),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createSurveyAnswerBody)
  }
);}




export const getCreateSurveyAnswerMutationOptions = <TError = Problem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSurveyAnswer>>, TError,{slug: string;data?: CreateSurveyAnswerBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createSurveyAnswer>>, TError,{slug: string;data?: CreateSurveyAnswerBody}, TContext> => {

const mutationKey = ['createSurveyAnswer'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSurveyAnswer>>, {slug: string;data?: CreateSurveyAnswerBody}> = (props) => {
          const {slug,data} = props ?? {};

          return  createSurveyAnswer(slug,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateSurveyAnswerMutationResult = NonNullable<Awaited<ReturnType<typeof createSurveyAnswer>>>
    export type CreateSurveyAnswerMutationBody = CreateSurveyAnswerBody | undefined
    export type CreateSurveyAnswerMutationError = Problem

    /**
 * @summary Submit an answer to a survey
 */
export const useCreateSurveyAnswer = <TError = Problem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSurveyAnswer>>, TError,{slug: string;data?: CreateSurveyAnswerBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createSurveyAnswer>>,
        TError,
        {slug: string;data?: CreateSurveyAnswerBody},
        TContext
      > => {
      return useMutation(getCreateSurveyAnswerMutationOptions(options));
    }
    export const getGetAllSurveyAnswersUrl = (slug: string,) => {




  return `/api/v1/surveys/${slug}/answers`
}

/**
 * @summary Get all answers of a survey
 */
export const getAllSurveyAnswers = async (slug: string, options?: RequestInit): Promise<GetAllSurveyAnswers200> => {

  return customInstance<GetAllSurveyAnswers200>(getGetAllSurveyAnswersUrl(slug),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAllSurveyAnswersQueryKey = (slug: string,) => {
    return [
    `/api/v1/surveys/${slug}/answers`
    ] as const;
    }


export const getGetAllSurveyAnswersQueryOptions = <TData = Awaited<ReturnType<typeof getAllSurveyAnswers>>, TError = Problem>(slug: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllSurveyAnswers>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllSurveyAnswersQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllSurveyAnswers>>> = ({ signal }) => getAllSurveyAnswers(slug, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllSurveyAnswers>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllSurveyAnswersQueryResult = NonNullable<Awaited<ReturnType<typeof getAllSurveyAnswers>>>
export type GetAllSurveyAnswersQueryError = Problem


/**
 * @summary Get all answers of a survey
 */

export function useGetAllSurveyAnswers<TData = Awaited<ReturnType<typeof getAllSurveyAnswers>>, TError = Problem>(
 slug: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllSurveyAnswers>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAllSurveyAnswersQueryOptions(slug,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getGetSurveyAnswerByIdUrl = (slug: string,
    id: string,) => {




  return `/api/v1/surveys/${slug}/answers/${id}`
}

/**
 * @summary Get an answer by id
 */
export const getSurveyAnswerById = async (slug: string,
    id: string, options?: RequestInit): Promise<GetSurveyAnswerById200> => {

  return customInstance<GetSurveyAnswerById200>(getGetSurveyAnswerByIdUrl(slug,id),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSurveyAnswerByIdQueryKey = (slug: string,
    id: string,) => {
    return [
    `/api/v1/surveys/${slug}/answers/${id}`
    ] as const;
    }


export const getGetSurveyAnswerByIdQueryOptions = <TData = Awaited<ReturnType<typeof getSurveyAnswerById>>, TError = Problem>(slug: string,
    id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSurveyAnswerById>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSurveyAnswerByIdQueryKey(slug,id);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSurveyAnswerById>>> = ({ signal }) => getSurveyAnswerById(slug,id, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined && id !== null && id !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSurveyAnswerById>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSurveyAnswerByIdQueryResult = NonNullable<Awaited<ReturnType<typeof getSurveyAnswerById>>>
export type GetSurveyAnswerByIdQueryError = Problem


/**
 * @summary Get an answer by id
 */

export function useGetSurveyAnswerById<TData = Awaited<ReturnType<typeof getSurveyAnswerById>>, TError = Problem>(
 slug: string,
    id: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSurveyAnswerById>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetSurveyAnswerByIdQueryOptions(slug,id,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getDeleteSurveyAnswerByIdUrl = (slug: string,
    id: string,) => {




  return `/api/v1/surveys/${slug}/answers/${id}`
}

/**
 * @summary Delete an answer by id
 */
export const deleteSurveyAnswerById = async (slug: string,
    id: string, options?: RequestInit): Promise<void> => {

  return customInstance<void>(getDeleteSurveyAnswerByIdUrl(slug,id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteSurveyAnswerByIdMutationOptions = <TError = Problem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSurveyAnswerById>>, TError,{slug: string;id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSurveyAnswerById>>, TError,{slug: string;id: string}, TContext> => {

const mutationKey = ['deleteSurveyAnswerById'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSurveyAnswerById>>, {slug: string;id: string}> = (props) => {
          const {slug,id} = props ?? {};

          return  deleteSurveyAnswerById(slug,id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteSurveyAnswerByIdMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSurveyAnswerById>>>

    export type DeleteSurveyAnswerByIdMutationError = Problem

    /**
 * @summary Delete an answer by id
 */
export const useDeleteSurveyAnswerById = <TError = Problem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSurveyAnswerById>>, TError,{slug: string;id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteSurveyAnswerById>>,
        TError,
        {slug: string;id: string},
        TContext
      > => {
      return useMutation(getDeleteSurveyAnswerByIdMutationOptions(options));
    }
