/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Survey System API
 * API endpoints documentation for the Survey System, built by Daxho
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  AcceptInvitation,
  AcceptInvitation201,
  CreateInvitation,
  CreateInvitation201,
  GetAllInvitations200,
  GetInvitationByToken200,
  Problem
} from '../surveySystemAPI.schemas';

import { customInstance } from '.././mutator/customInstance';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getCreateInvitationUrl = () => {




  return `/api/v1/invitations`
}

/**
 * Replaces a pending invitation for the same email. The token is returned only here; the link is /auth/invite/{token}.
 * @summary Invite an email to create an account
 */
export const createInvitation = async (createInvitation?: CreateInvitation, options?: RequestInit): Promise<CreateInvitation201> => {

  return customInstance<CreateInvitation201>(getCreateInvitationUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createInvitation)
  }
);}




export const getCreateInvitationMutationOptions = <TError = Problem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createInvitation>>, TError,{data?: CreateInvitation}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createInvitation>>, TError,{data?: CreateInvitation}, TContext> => {

const mutationKey = ['createInvitation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createInvitation>>, {data?: CreateInvitation}> = (props) => {
          const {data} = props ?? {};

          return  createInvitation(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateInvitationMutationResult = NonNullable<Awaited<ReturnType<typeof createInvitation>>>
    export type CreateInvitationMutationBody = CreateInvitation | undefined
    export type CreateInvitationMutationError = Problem

    /**
 * @summary Invite an email to create an account
 */
export const useCreateInvitation = <TError = Problem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createInvitation>>, TError,{data?: CreateInvitation}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createInvitation>>,
        TError,
        {data?: CreateInvitation},
        TContext
      > => {
      return useMutation(getCreateInvitationMutationOptions(options));
    }
    export const getGetAllInvitationsUrl = () => {




  return `/api/v1/invitations`
}

/**
 * @summary List invitations
 */
export const getAllInvitations = async ( options?: RequestInit): Promise<GetAllInvitations200> => {

  return customInstance<GetAllInvitations200>(getGetAllInvitationsUrl(),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAllInvitationsQueryKey = () => {
    return [
    `/api/v1/invitations`
    ] as const;
    }


export const getGetAllInvitationsQueryOptions = <TData = Awaited<ReturnType<typeof getAllInvitations>>, TError = Problem>( options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllInvitations>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllInvitationsQueryKey();



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllInvitations>>> = ({ signal }) => getAllInvitations({ signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllInvitations>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllInvitationsQueryResult = NonNullable<Awaited<ReturnType<typeof getAllInvitations>>>
export type GetAllInvitationsQueryError = Problem


/**
 * @summary List invitations
 */

export function useGetAllInvitations<TData = Awaited<ReturnType<typeof getAllInvitations>>, TError = Problem>(
  options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllInvitations>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAllInvitationsQueryOptions(options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getRevokeInvitationUrl = (id: string,) => {




  return `/api/v1/invitations/${id}`
}

/**
 * @summary Revoke a pending invitation
 */
export const revokeInvitation = async (id: string, options?: RequestInit): Promise<void> => {

  return customInstance<void>(getRevokeInvitationUrl(id),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getRevokeInvitationMutationOptions = <TError = Problem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeInvitation>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof revokeInvitation>>, TError,{id: string}, TContext> => {

const mutationKey = ['revokeInvitation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof revokeInvitation>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  revokeInvitation(id,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type RevokeInvitationMutationResult = NonNullable<Awaited<ReturnType<typeof revokeInvitation>>>

    export type RevokeInvitationMutationError = Problem

    /**
 * @summary Revoke a pending invitation
 */
export const useRevokeInvitation = <TError = Problem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof revokeInvitation>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof revokeInvitation>>,
        TError,
        {id: string},
        TContext
      > => {
      return useMutation(getRevokeInvitationMutationOptions(options));
    }
    export const getGetInvitationByTokenUrl = (token: string,) => {




  return `/api/v1/invitations/token/${token}`
}

/**
 * @summary Get a pending invitation by token
 */
export const getInvitationByToken = async (token: string, options?: RequestInit): Promise<GetInvitationByToken200> => {

  return customInstance<GetInvitationByToken200>(getGetInvitationByTokenUrl(token),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetInvitationByTokenQueryKey = (token: string,) => {
    return [
    `/api/v1/invitations/token/${token}`
    ] as const;
    }


export const getGetInvitationByTokenQueryOptions = <TData = Awaited<ReturnType<typeof getInvitationByToken>>, TError = Problem>(token: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getInvitationByToken>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetInvitationByTokenQueryKey(token);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getInvitationByToken>>> = ({ signal }) => getInvitationByToken(token, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: token !== null && token !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getInvitationByToken>>, TError, TData> & { queryKey: QueryKey }
}

export type GetInvitationByTokenQueryResult = NonNullable<Awaited<ReturnType<typeof getInvitationByToken>>>
export type GetInvitationByTokenQueryError = Problem


/**
 * @summary Get a pending invitation by token
 */

export function useGetInvitationByToken<TData = Awaited<ReturnType<typeof getInvitationByToken>>, TError = Problem>(
 token: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getInvitationByToken>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetInvitationByTokenQueryOptions(token,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getAcceptInvitationUrl = (token: string,) => {




  return `/api/v1/invitations/token/${token}/accept`
}

/**
 * @summary Create the account of an invitation
 */
export const acceptInvitation = async (token: string,
    acceptInvitation?: AcceptInvitation, options?: RequestInit): Promise<AcceptInvitation201> => {

  return customInstance<AcceptInvitation201>(getAcceptInvitationUrl(token),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(acceptInvitation)
  }
);}




export const getAcceptInvitationMutationOptions = <TError = Problem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof acceptInvitation>>, TError,{token: string;data?: AcceptInvitation}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof acceptInvitation>>, TError,{token: string;data?: AcceptInvitation}, TContext> => {

const mutationKey = ['acceptInvitation'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof acceptInvitation>>, {token: string;data?: AcceptInvitation}> = (props) => {
          const {token,data} = props ?? {};

          return  acceptInvitation(token,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type AcceptInvitationMutationResult = NonNullable<Awaited<ReturnType<typeof acceptInvitation>>>
    export type AcceptInvitationMutationBody = AcceptInvitation | undefined
    export type AcceptInvitationMutationError = Problem

    /**
 * @summary Create the account of an invitation
 */
export const useAcceptInvitation = <TError = Problem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof acceptInvitation>>, TError,{token: string;data?: AcceptInvitation}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof acceptInvitation>>,
        TError,
        {token: string;data?: AcceptInvitation},
        TContext
      > => {
      return useMutation(getAcceptInvitationMutationOptions(options));
    }
