/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Survey System API
 * API endpoints documentation for the Survey System, built by Daxho
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateSurvey,
  Error,
  GetAllSurveysParams,
  Survey,
  SurveyStats,
  UpdateSurveyBySlugBody
} from '../surveySystemAPI.schemas';

import { customInstance } from '.././mutator/customInstance';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export type getAllSurveysResponse200 = {
  data: Survey[]
  status: 200
}

export type getAllSurveysResponse400 = {
  data: Error
  status: 400
}

export type getAllSurveysResponse401 = {
  data: Error
  status: 401
}

export type getAllSurveysResponse404 = {
  data: Error
  status: 404
}

export type getAllSurveysResponse422 = {
  data: Error
  status: 422
}

export type getAllSurveysResponse500 = {
  data: Error
  status: 500
}

export type getAllSurveysResponseSuccess = (getAllSurveysResponse200) & {
  headers: Headers;
};
export type getAllSurveysResponseError = (getAllSurveysResponse400 | getAllSurveysResponse401 | getAllSurveysResponse404 | getAllSurveysResponse422 | getAllSurveysResponse500) & {
  headers: Headers;
};

export type getAllSurveysResponse = (getAllSurveysResponseSuccess | getAllSurveysResponseError)

export const getGetAllSurveysUrl = (params?: GetAllSurveysParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `http://localhost:3000/api/v1/surveys?${stringifiedParams}` : `http://localhost:3000/api/v1/surveys`
}

/**
 * @summary Get all surveys
 */
export const getAllSurveys = async (params?: GetAllSurveysParams, options?: RequestInit): Promise<getAllSurveysResponse> => {

  return customInstance<getAllSurveysResponse>(getGetAllSurveysUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAllSurveysQueryKey = (params?: GetAllSurveysParams,) => {
    return [
    `http://localhost:3000/api/v1/surveys`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAllSurveysQueryOptions = <TData = Awaited<ReturnType<typeof getAllSurveys>>, TError = Error>(params?: GetAllSurveysParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllSurveys>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllSurveysQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllSurveys>>> = ({ signal }) => getAllSurveys(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllSurveys>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllSurveysQueryResult = NonNullable<Awaited<ReturnType<typeof getAllSurveys>>>
export type GetAllSurveysQueryError = Error


/**
 * @summary Get all surveys
 */

export function useGetAllSurveys<TData = Awaited<ReturnType<typeof getAllSurveys>>, TError = Error>(
 params?: GetAllSurveysParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllSurveys>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAllSurveysQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type createSurveyResponse201 = {
  data: Survey
  status: 201
}

export type createSurveyResponse400 = {
  data: Error
  status: 400
}

export type createSurveyResponse401 = {
  data: Error
  status: 401
}

export type createSurveyResponse404 = {
  data: Error
  status: 404
}

export type createSurveyResponse422 = {
  data: Error
  status: 422
}

export type createSurveyResponse500 = {
  data: Error
  status: 500
}

export type createSurveyResponseSuccess = (createSurveyResponse201) & {
  headers: Headers;
};
export type createSurveyResponseError = (createSurveyResponse400 | createSurveyResponse401 | createSurveyResponse404 | createSurveyResponse422 | createSurveyResponse500) & {
  headers: Headers;
};

export type createSurveyResponse = (createSurveyResponseSuccess | createSurveyResponseError)

export const getCreateSurveyUrl = () => {




  return `http://localhost:3000/api/v1/surveys`
}

/**
 * @summary Create a new survey
 */
export const createSurvey = async (createSurvey?: CreateSurvey, options?: RequestInit): Promise<createSurveyResponse> => {

  return customInstance<createSurveyResponse>(getCreateSurveyUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createSurvey)
  }
);}




export const getCreateSurveyMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSurvey>>, TError,{data?: CreateSurvey}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createSurvey>>, TError,{data?: CreateSurvey}, TContext> => {

const mutationKey = ['createSurvey'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSurvey>>, {data?: CreateSurvey}> = (props) => {
          const {data} = props ?? {};

          return  createSurvey(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateSurveyMutationResult = NonNullable<Awaited<ReturnType<typeof createSurvey>>>
    export type CreateSurveyMutationBody = CreateSurvey | undefined
    export type CreateSurveyMutationError = Error

    /**
 * @summary Create a new survey
 */
export const useCreateSurvey = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSurvey>>, TError,{data?: CreateSurvey}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createSurvey>>,
        TError,
        {data?: CreateSurvey},
        TContext
      > => {
      return useMutation(getCreateSurveyMutationOptions(options));
    }
    export type getSurveyBySlugResponse200 = {
  data: Survey
  status: 200
}

export type getSurveyBySlugResponse400 = {
  data: Error
  status: 400
}

export type getSurveyBySlugResponse401 = {
  data: Error
  status: 401
}

export type getSurveyBySlugResponse404 = {
  data: Error
  status: 404
}

export type getSurveyBySlugResponse422 = {
  data: Error
  status: 422
}

export type getSurveyBySlugResponse500 = {
  data: Error
  status: 500
}

export type getSurveyBySlugResponseSuccess = (getSurveyBySlugResponse200) & {
  headers: Headers;
};
export type getSurveyBySlugResponseError = (getSurveyBySlugResponse400 | getSurveyBySlugResponse401 | getSurveyBySlugResponse404 | getSurveyBySlugResponse422 | getSurveyBySlugResponse500) & {
  headers: Headers;
};

export type getSurveyBySlugResponse = (getSurveyBySlugResponseSuccess | getSurveyBySlugResponseError)

export const getGetSurveyBySlugUrl = (slug: string,) => {




  return `http://localhost:3000/api/v1/surveys/${slug}`
}

/**
 * @summary Get survey by slug
 */
export const getSurveyBySlug = async (slug: string, options?: RequestInit): Promise<getSurveyBySlugResponse> => {

  return customInstance<getSurveyBySlugResponse>(getGetSurveyBySlugUrl(slug),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSurveyBySlugQueryKey = (slug: string,) => {
    return [
    `http://localhost:3000/api/v1/surveys/${slug}`
    ] as const;
    }


export const getGetSurveyBySlugQueryOptions = <TData = Awaited<ReturnType<typeof getSurveyBySlug>>, TError = Error>(slug: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSurveyBySlug>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSurveyBySlugQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSurveyBySlug>>> = ({ signal }) => getSurveyBySlug(slug, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSurveyBySlug>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSurveyBySlugQueryResult = NonNullable<Awaited<ReturnType<typeof getSurveyBySlug>>>
export type GetSurveyBySlugQueryError = Error


/**
 * @summary Get survey by slug
 */

export function useGetSurveyBySlug<TData = Awaited<ReturnType<typeof getSurveyBySlug>>, TError = Error>(
 slug: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSurveyBySlug>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetSurveyBySlugQueryOptions(slug,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export type updateSurveyBySlugResponse200 = {
  data: Survey
  status: 200
}

export type updateSurveyBySlugResponse400 = {
  data: Error
  status: 400
}

export type updateSurveyBySlugResponse401 = {
  data: Error
  status: 401
}

export type updateSurveyBySlugResponse404 = {
  data: Error
  status: 404
}

export type updateSurveyBySlugResponse422 = {
  data: Error
  status: 422
}

export type updateSurveyBySlugResponse500 = {
  data: Error
  status: 500
}

export type updateSurveyBySlugResponseSuccess = (updateSurveyBySlugResponse200) & {
  headers: Headers;
};
export type updateSurveyBySlugResponseError = (updateSurveyBySlugResponse400 | updateSurveyBySlugResponse401 | updateSurveyBySlugResponse404 | updateSurveyBySlugResponse422 | updateSurveyBySlugResponse500) & {
  headers: Headers;
};

export type updateSurveyBySlugResponse = (updateSurveyBySlugResponseSuccess | updateSurveyBySlugResponseError)

export const getUpdateSurveyBySlugUrl = (slug: string,) => {




  return `http://localhost:3000/api/v1/surveys/${slug}`
}

/**
 * @summary Update survey by slug
 */
export const updateSurveyBySlug = async (slug: string,
    updateSurveyBySlugBody?: UpdateSurveyBySlugBody, options?: RequestInit): Promise<updateSurveyBySlugResponse> => {

  return customInstance<updateSurveyBySlugResponse>(getUpdateSurveyBySlugUrl(slug),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateSurveyBySlugBody)
  }
);}




export const getUpdateSurveyBySlugMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSurveyBySlug>>, TError,{slug: string;data?: UpdateSurveyBySlugBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateSurveyBySlug>>, TError,{slug: string;data?: UpdateSurveyBySlugBody}, TContext> => {

const mutationKey = ['updateSurveyBySlug'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSurveyBySlug>>, {slug: string;data?: UpdateSurveyBySlugBody}> = (props) => {
          const {slug,data} = props ?? {};

          return  updateSurveyBySlug(slug,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateSurveyBySlugMutationResult = NonNullable<Awaited<ReturnType<typeof updateSurveyBySlug>>>
    export type UpdateSurveyBySlugMutationBody = UpdateSurveyBySlugBody | undefined
    export type UpdateSurveyBySlugMutationError = Error

    /**
 * @summary Update survey by slug
 */
export const useUpdateSurveyBySlug = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSurveyBySlug>>, TError,{slug: string;data?: UpdateSurveyBySlugBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateSurveyBySlug>>,
        TError,
        {slug: string;data?: UpdateSurveyBySlugBody},
        TContext
      > => {
      return useMutation(getUpdateSurveyBySlugMutationOptions(options));
    }
    export type deleteSurveyBySlugResponse204 = {
  data: void
  status: 204
}

export type deleteSurveyBySlugResponse400 = {
  data: Error
  status: 400
}

export type deleteSurveyBySlugResponse401 = {
  data: Error
  status: 401
}

export type deleteSurveyBySlugResponse404 = {
  data: Error
  status: 404
}

export type deleteSurveyBySlugResponse422 = {
  data: Error
  status: 422
}

export type deleteSurveyBySlugResponse500 = {
  data: Error
  status: 500
}

export type deleteSurveyBySlugResponseSuccess = (deleteSurveyBySlugResponse204) & {
  headers: Headers;
};
export type deleteSurveyBySlugResponseError = (deleteSurveyBySlugResponse400 | deleteSurveyBySlugResponse401 | deleteSurveyBySlugResponse404 | deleteSurveyBySlugResponse422 | deleteSurveyBySlugResponse500) & {
  headers: Headers;
};

export type deleteSurveyBySlugResponse = (deleteSurveyBySlugResponseSuccess | deleteSurveyBySlugResponseError)

export const getDeleteSurveyBySlugUrl = (slug: string,) => {




  return `http://localhost:3000/api/v1/surveys/${slug}`
}

/**
 * @summary Delete survey by slug
 */
export const deleteSurveyBySlug = async (slug: string, options?: RequestInit): Promise<deleteSurveyBySlugResponse> => {

  return customInstance<deleteSurveyBySlugResponse>(getDeleteSurveyBySlugUrl(slug),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteSurveyBySlugMutationOptions = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSurveyBySlug>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSurveyBySlug>>, TError,{slug: string}, TContext> => {

const mutationKey = ['deleteSurveyBySlug'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSurveyBySlug>>, {slug: string}> = (props) => {
          const {slug} = props ?? {};

          return  deleteSurveyBySlug(slug,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteSurveyBySlugMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSurveyBySlug>>>

    export type DeleteSurveyBySlugMutationError = Error

    /**
 * @summary Delete survey by slug
 */
export const useDeleteSurveyBySlug = <TError = Error,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSurveyBySlug>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteSurveyBySlug>>,
        TError,
        {slug: string},
        TContext
      > => {
      return useMutation(getDeleteSurveyBySlugMutationOptions(options));
    }
    export type getSurveyStatsBySlugResponse200 = {
  data: SurveyStats
  status: 200
}

export type getSurveyStatsBySlugResponse400 = {
  data: Error
  status: 400
}

export type getSurveyStatsBySlugResponse401 = {
  data: Error
  status: 401
}

export type getSurveyStatsBySlugResponse404 = {
  data: Error
  status: 404
}

export type getSurveyStatsBySlugResponse422 = {
  data: Error
  status: 422
}

export type getSurveyStatsBySlugResponse500 = {
  data: Error
  status: 500
}

export type getSurveyStatsBySlugResponseSuccess = (getSurveyStatsBySlugResponse200) & {
  headers: Headers;
};
export type getSurveyStatsBySlugResponseError = (getSurveyStatsBySlugResponse400 | getSurveyStatsBySlugResponse401 | getSurveyStatsBySlugResponse404 | getSurveyStatsBySlugResponse422 | getSurveyStatsBySlugResponse500) & {
  headers: Headers;
};

export type getSurveyStatsBySlugResponse = (getSurveyStatsBySlugResponseSuccess | getSurveyStatsBySlugResponseError)

export const getGetSurveyStatsBySlugUrl = (slug: string,) => {




  return `http://localhost:3000/api/v1/surveys/${slug}/stats`
}

/**
 * @summary Get survey stats by slug
 */
export const getSurveyStatsBySlug = async (slug: string, options?: RequestInit): Promise<getSurveyStatsBySlugResponse> => {

  return customInstance<getSurveyStatsBySlugResponse>(getGetSurveyStatsBySlugUrl(slug),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSurveyStatsBySlugQueryKey = (slug: string,) => {
    return [
    `http://localhost:3000/api/v1/surveys/${slug}/stats`
    ] as const;
    }


export const getGetSurveyStatsBySlugQueryOptions = <TData = Awaited<ReturnType<typeof getSurveyStatsBySlug>>, TError = Error>(slug: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSurveyStatsBySlug>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSurveyStatsBySlugQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSurveyStatsBySlug>>> = ({ signal }) => getSurveyStatsBySlug(slug, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSurveyStatsBySlug>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSurveyStatsBySlugQueryResult = NonNullable<Awaited<ReturnType<typeof getSurveyStatsBySlug>>>
export type GetSurveyStatsBySlugQueryError = Error


/**
 * @summary Get survey stats by slug
 */

export function useGetSurveyStatsBySlug<TData = Awaited<ReturnType<typeof getSurveyStatsBySlug>>, TError = Error>(
 slug: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSurveyStatsBySlug>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetSurveyStatsBySlugQueryOptions(slug,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






