/**
 * Generated by orval v8.17.0 🍺
 * Do not edit manually.
 * Survey System API
 * API endpoints documentation for the Survey System, built by Daxho
 * OpenAPI spec version: 1.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  MutationFunction,
  QueryFunction,
  QueryKey,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import type {
  CreateSurvey,
  CreateSurvey201,
  GetAllSurveys200,
  GetAllSurveysParams,
  GetSurveyBySlug200,
  GetSurveyStatsBySlug200,
  Problem,
  UpdateSurveyBySlug200,
  UpdateSurveyBySlugBody
} from '../surveySystemAPI.schemas';

import { customInstance } from '.././mutator/customInstance';

type AwaitedInput<T> = PromiseLike<T> | T;

      type Awaited<O> = O extends AwaitedInput<infer T> ? T : never;


type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const getGetAllSurveysUrl = (params?: GetAllSurveysParams,) => {
  const normalizedParams = new URLSearchParams();

  Object.entries(params || {}).forEach(([key, value]) => {

    if (value !== undefined) {
      normalizedParams.append(key, value === null ? 'null' : String(value))
    }
  });

  const stringifiedParams = normalizedParams.toString();

  return stringifiedParams.length > 0 ? `/api/v1/surveys?${stringifiedParams}` : `/api/v1/surveys`
}

/**
 * @summary Get all surveys
 */
export const getAllSurveys = async (params?: GetAllSurveysParams, options?: RequestInit): Promise<GetAllSurveys200> => {

  return customInstance<GetAllSurveys200>(getGetAllSurveysUrl(params),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetAllSurveysQueryKey = (params?: GetAllSurveysParams,) => {
    return [
    `/api/v1/surveys`, ...(params ? [params] : [])
    ] as const;
    }


export const getGetAllSurveysQueryOptions = <TData = Awaited<ReturnType<typeof getAllSurveys>>, TError = Problem>(params?: GetAllSurveysParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllSurveys>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetAllSurveysQueryKey(params);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getAllSurveys>>> = ({ signal }) => getAllSurveys(params, { signal, ...requestOptions });





   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getAllSurveys>>, TError, TData> & { queryKey: QueryKey }
}

export type GetAllSurveysQueryResult = NonNullable<Awaited<ReturnType<typeof getAllSurveys>>>
export type GetAllSurveysQueryError = Problem


/**
 * @summary Get all surveys
 */

export function useGetAllSurveys<TData = Awaited<ReturnType<typeof getAllSurveys>>, TError = Problem>(
 params?: GetAllSurveysParams, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getAllSurveys>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetAllSurveysQueryOptions(params,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getCreateSurveyUrl = () => {




  return `/api/v1/surveys`
}

/**
 * @summary Create a new survey
 */
export const createSurvey = async (createSurvey?: CreateSurvey, options?: RequestInit): Promise<CreateSurvey201> => {

  return customInstance<CreateSurvey201>(getCreateSurveyUrl(),
  {
    ...options,
    method: 'POST',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(createSurvey)
  }
);}




export const getCreateSurveyMutationOptions = <TError = Problem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSurvey>>, TError,{data?: CreateSurvey}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof createSurvey>>, TError,{data?: CreateSurvey}, TContext> => {

const mutationKey = ['createSurvey'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createSurvey>>, {data?: CreateSurvey}> = (props) => {
          const {data} = props ?? {};

          return  createSurvey(data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type CreateSurveyMutationResult = NonNullable<Awaited<ReturnType<typeof createSurvey>>>
    export type CreateSurveyMutationBody = CreateSurvey | undefined
    export type CreateSurveyMutationError = Problem

    /**
 * @summary Create a new survey
 */
export const useCreateSurvey = <TError = Problem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createSurvey>>, TError,{data?: CreateSurvey}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof createSurvey>>,
        TError,
        {data?: CreateSurvey},
        TContext
      > => {
      return useMutation(getCreateSurveyMutationOptions(options));
    }
    export const getGetSurveyBySlugUrl = (slug: string,) => {




  return `/api/v1/surveys/${slug}`
}

/**
 * Public. Inactive surveys are only returned with a session; an expired session on an inactive survey gets 401 so the client can refresh (SURV-12).
 * @summary Get survey by slug
 */
export const getSurveyBySlug = async (slug: string, options?: RequestInit): Promise<GetSurveyBySlug200> => {

  return customInstance<GetSurveyBySlug200>(getGetSurveyBySlugUrl(slug),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSurveyBySlugQueryKey = (slug: string,) => {
    return [
    `/api/v1/surveys/${slug}`
    ] as const;
    }


export const getGetSurveyBySlugQueryOptions = <TData = Awaited<ReturnType<typeof getSurveyBySlug>>, TError = Problem>(slug: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSurveyBySlug>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSurveyBySlugQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSurveyBySlug>>> = ({ signal }) => getSurveyBySlug(slug, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSurveyBySlug>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSurveyBySlugQueryResult = NonNullable<Awaited<ReturnType<typeof getSurveyBySlug>>>
export type GetSurveyBySlugQueryError = Problem


/**
 * @summary Get survey by slug
 */

export function useGetSurveyBySlug<TData = Awaited<ReturnType<typeof getSurveyBySlug>>, TError = Problem>(
 slug: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSurveyBySlug>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetSurveyBySlugQueryOptions(slug,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






export const getUpdateSurveyBySlugUrl = (slug: string,) => {




  return `/api/v1/surveys/${slug}`
}

/**
 * @summary Update survey by slug
 */
export const updateSurveyBySlug = async (slug: string,
    updateSurveyBySlugBody?: UpdateSurveyBySlugBody, options?: RequestInit): Promise<UpdateSurveyBySlug200> => {

  return customInstance<UpdateSurveyBySlug200>(getUpdateSurveyBySlugUrl(slug),
  {
    ...options,
    method: 'PATCH',
    headers: { 'Content-Type': 'application/json', ...options?.headers },
    body: JSON.stringify(updateSurveyBySlugBody)
  }
);}




export const getUpdateSurveyBySlugMutationOptions = <TError = Problem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSurveyBySlug>>, TError,{slug: string;data?: UpdateSurveyBySlugBody}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof updateSurveyBySlug>>, TError,{slug: string;data?: UpdateSurveyBySlugBody}, TContext> => {

const mutationKey = ['updateSurveyBySlug'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateSurveyBySlug>>, {slug: string;data?: UpdateSurveyBySlugBody}> = (props) => {
          const {slug,data} = props ?? {};

          return  updateSurveyBySlug(slug,data,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type UpdateSurveyBySlugMutationResult = NonNullable<Awaited<ReturnType<typeof updateSurveyBySlug>>>
    export type UpdateSurveyBySlugMutationBody = UpdateSurveyBySlugBody | undefined
    export type UpdateSurveyBySlugMutationError = Problem

    /**
 * @summary Update survey by slug
 */
export const useUpdateSurveyBySlug = <TError = Problem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateSurveyBySlug>>, TError,{slug: string;data?: UpdateSurveyBySlugBody}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof updateSurveyBySlug>>,
        TError,
        {slug: string;data?: UpdateSurveyBySlugBody},
        TContext
      > => {
      return useMutation(getUpdateSurveyBySlugMutationOptions(options));
    }
    export const getDeleteSurveyBySlugUrl = (slug: string,) => {




  return `/api/v1/surveys/${slug}`
}

/**
 * @summary Delete survey by slug
 */
export const deleteSurveyBySlug = async (slug: string, options?: RequestInit): Promise<void> => {

  return customInstance<void>(getDeleteSurveyBySlugUrl(slug),
  {
    ...options,
    method: 'DELETE'


  }
);}




export const getDeleteSurveyBySlugMutationOptions = <TError = Problem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSurveyBySlug>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof customInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof deleteSurveyBySlug>>, TError,{slug: string}, TContext> => {

const mutationKey = ['deleteSurveyBySlug'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};




      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteSurveyBySlug>>, {slug: string}> = (props) => {
          const {slug} = props ?? {};

          return  deleteSurveyBySlug(slug,requestOptions)
        }






  return  { mutationFn, ...mutationOptions }}

    export type DeleteSurveyBySlugMutationResult = NonNullable<Awaited<ReturnType<typeof deleteSurveyBySlug>>>

    export type DeleteSurveyBySlugMutationError = Problem

    /**
 * @summary Delete survey by slug
 */
export const useDeleteSurveyBySlug = <TError = Problem,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteSurveyBySlug>>, TError,{slug: string}, TContext>, request?: SecondParameter<typeof customInstance>}
 ): UseMutationResult<
        Awaited<ReturnType<typeof deleteSurveyBySlug>>,
        TError,
        {slug: string},
        TContext
      > => {
      return useMutation(getDeleteSurveyBySlugMutationOptions(options));
    }
    export const getGetSurveyStatsBySlugUrl = (slug: string,) => {




  return `/api/v1/surveys/${slug}/stats`
}

/**
 * @summary Get survey statistics
 */
export const getSurveyStatsBySlug = async (slug: string, options?: RequestInit): Promise<GetSurveyStatsBySlug200> => {

  return customInstance<GetSurveyStatsBySlug200>(getGetSurveyStatsBySlugUrl(slug),
  {
    ...options,
    method: 'GET'


  }
);}





export const getGetSurveyStatsBySlugQueryKey = (slug: string,) => {
    return [
    `/api/v1/surveys/${slug}/stats`
    ] as const;
    }


export const getGetSurveyStatsBySlugQueryOptions = <TData = Awaited<ReturnType<typeof getSurveyStatsBySlug>>, TError = Problem>(slug: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSurveyStatsBySlug>>, TError, TData>, request?: SecondParameter<typeof customInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSurveyStatsBySlugQueryKey(slug);



    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSurveyStatsBySlug>>> = ({ signal }) => getSurveyStatsBySlug(slug, { signal, ...requestOptions });





   return  { queryKey, queryFn, enabled: slug !== null && slug !== undefined, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSurveyStatsBySlug>>, TError, TData> & { queryKey: QueryKey }
}

export type GetSurveyStatsBySlugQueryResult = NonNullable<Awaited<ReturnType<typeof getSurveyStatsBySlug>>>
export type GetSurveyStatsBySlugQueryError = Problem


/**
 * @summary Get survey statistics
 */

export function useGetSurveyStatsBySlug<TData = Awaited<ReturnType<typeof getSurveyStatsBySlug>>, TError = Problem>(
 slug: string, options?: { query?:UseQueryOptions<Awaited<ReturnType<typeof getSurveyStatsBySlug>>, TError, TData>, request?: SecondParameter<typeof customInstance>}

 ):  UseQueryResult<TData, TError> & { queryKey: QueryKey } {

  const queryOptions = getGetSurveyStatsBySlugQueryOptions(slug,options)

  const query = useQuery(queryOptions) as  UseQueryResult<TData, TError> & { queryKey: QueryKey };

  return { ...query, queryKey: queryOptions.queryKey };
}






